export const metadata = {
  title: 'CareMates',
  description: 'Dashboard monitoring pasien dan caregiver',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: 'Poppins, sans-serif' }}>
        <header
          style={{
            padding: '0px',
            backgroundColor: '#7b42f6',
            color: 'white',
            fontWeight: 'bold',
            fontSize: '1.5rem',
          }}
        >
        </header>
        <main style={{ padding: '20px', minHeight: 'calc(100vh - 120px)' }}>
          {children}
        </main>
        <footer
          style={{
            padding: '20px',
            textAlign: 'center',
            color: '#888',
            borderTop: '1px solid #ddd',
            fontSize: '0.9rem',
          }}
        >
          &copy; 2025 CareMates. All rights reserved.
        </footer>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }